version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app:Z #:Z is for SELinux compatibility remove if not needed
    ports:
      - "8501:8501"
    depends_on:
      - mlflow
      - prefect
    command: streamlit run app/streamlit_app.py --server.port=8501 --server.enableCORS=false --server.enableXsrfProtection=false

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: mlflow server --host 0.0.0.0 --port 5000

  prefect:
    image: docker.io/prefecthq/prefect:2.20.18-python3.12
    ports:
      - "4200:4200"
    environment:
      - PREFECT_UI_URL=http://localhost:4200
    entrypoint: ["prefect", "server", "start"]

  prefect-agent:
    image: docker.io/prefecthq/prefect:2.20.18-python3.12
    depends_on:
      - prefect
    working_dir: /app
    volumes:
      - .:/app:Z #:Z is for SELinux compatibility remove if not needed
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
    entrypoint: ["/bin/sh", "-c"]
    command: chmod +x /app/deploy.sh && /app/deploy.sh && prefect agent start --work-queue default
