stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - data/raw/
      - scripts/preprocess.py
    outs:
      - data/processed/

  inference:
    cmd: python scripts/inference.py
    deps:
      - data/processed/
      - models/emotion_model.pkl
      - scripts/inference.py
    outs:
      - data/inference_output/
      - metadata/inference_log.json

  evaluate:
    cmd: python scripts/evaluate_model.py
    deps:
      - metadata/inference_log.json
    outs: []